apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mp9-deployment
  labels:
    app: mp9
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mp9
  template:
    metadata:
      labels:
        app: mp9
    spec:
      containers:
      - name: mp9
        image: gcr.io/cs398-ianchin2-mp9/mp9
        ports:
        - containerPort: 8080
