kind: Service
apiVersion: v1
metadata:
  name: mp9
spec:
  selector:
    app: mp9
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 146.148.47.155
